### ISSUE TITLE
Error Loading

### ISSUE THREAD

**Issue by dlimanov** [no0be/DNSlivery#4]
Getting this on launch:
$ sudo python dnslivery.py eth0 -p /tmp/dns-delivery/ -v myevildomain.com ns1.myevildomain.com

DNSlivery - Easy files and payloads delivery over DNS

Traceback (most recent call last):
  File "dnslivery.py", line 153, in <module>
    if not args.size.isdecimal():
AttributeError: 'str' object has no attribute 'isdecimal'

If I delete all files in /tmp/dns-delivery/ directory, it will launch but obviously not do anything as there's nothing to serve. Is there a format/syntax that the files need to be, as it looks like python is processing them on load and breaks them down into a Base64 chunks. For some reason even a simplest "Hello World" text document prevents it from launching for me.
Thanks!

**Comment by no0be** [comment]
What python version are you using? Can you provide the output of the following command:
```
python --version
```

DNSlivery has been developed for python3 and will not work with python2. Try running the same command with python3 (if installed):
```
$ sudo python3 dnslivery.py eth0 -p /tmp/dns-delivery/ -v myevildomain.com ns1.myevildomain.com
```

---

The error is due to the fact that `isdecimal()` is only present on `unicode` objects in [python2](https://docs.python.org/2/library/stdtypes.html#unicode.isdecimal), while it is available for `str` objects in [python3](https://docs.python.org/3/library/stdtypes.html#str.isdecimal).
